wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.3
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 2
      4: 3.7.3
      5: 0.10.14
